; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Mar 18 2021 14:41:15 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAWHE89A12E8:
	dc.w DATAWHE89A12E8_0-DATAWHE89A12E8, DATAWHE89A12E8_1-DATAWHE89A12E8
	dc.w DATAWHE89A12E8_2-DATAWHE89A12E8, DATAWHE89A12E8_3-DATAWHE89A12E8
	dc.w DATAWHE89A12E8_4-DATAWHE89A12E8, DATAWHE89A12E8_5-DATAWHE89A12E8
DATAWHE89A12E8_0: dc.b $2
	dc.b $F0, $7, $40, $0, $F0
	dc.b $F0, $7, $48, $0, $0
DATAWHE89A12E8_1: dc.b $2
	dc.b $F0, $7, $40, $8, $F0
	dc.b $F0, $7, $48, $8, $0
DATAWHE89A12E8_2: dc.b $2
	dc.b $F0, $7, $40, $10, $F0
	dc.b $F0, $7, $48, $10, $0
DATAWHE89A12E8_3: dc.b $2
	dc.b $F0, $7, $40, $18, $F0
	dc.b $F0, $7, $48, $18, $0
DATAWHE89A12E8_4: dc.b $2
	dc.b $F0, $7, $40, $20, $F0
	dc.b $F0, $7, $48, $20, $0
DATAWHE89A12E8_5: dc.b $2
	dc.b $F0, $7, $40, $28, $F0
	dc.b $F0, $7, $48, $28, $0
	even